# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin_data.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'plugin_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11plugin_data.proto\x12\x1btensorboard.imfusion_viewer\"\xba\x02\n\x17ImFusionLayerPluginData\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\tcase_name\x18\x02 \x01(\t\x12\x12\n\nlayer_name\x18\x03 \x01(\t\x12\x34\n\x04kind\x18\x04 \x01(\x0e\x32&.tensorboard.imfusion_viewer.LayerKind\x12\x16\n\x0e\x66ile_extension\x18\x05 \x01(\t\x12\x17\n\x0fzlib_compressed\x18\x06 \x01(\x08\x12\x14\n\x0c\x64isplay_name\x18\x07 \x01(\t\x12\x15\n\rdefault_color\x18\x08 \x03(\x02\x12\x17\n\x0f\x64\x65\x66\x61ult_opacity\x18\t \x01(\x02\x12\x17\n\x0f\x64\x65\x66\x61ult_visible\x18\n \x01(\x08\x12\r\n\x05order\x18\x0b \x01(\x05\x12\x12\n\njson_extra\x18\x0c \x01(\t*F\n\tLayerKind\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06VOLUME\x10\x01\x12\x08\n\x04MASK\x10\x02\x12\x08\n\x04MESH\x10\x03\x12\x0c\n\x08IMAGE_2D\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAYERKIND']._serialized_start=367
  _globals['_LAYERKIND']._serialized_end=437
  _globals['_IMFUSIONLAYERPLUGINDATA']._serialized_start=51
  _globals['_IMFUSIONLAYERPLUGINDATA']._serialized_end=365
# @@protoc_insertion_point(module_scope)
